### ISSUE TITLE
Add Sky Diversity as alternate

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#75]
Don't know how it works, someone just mentioned it. Needs to be looked into: https://www.nexusmods.com/morrowind/mods/44345?

**Comment by Tyler799** [comment]
Actually, this likely isn't worth our time. From what I can tell, it's actually very complicated to use with lots of moving parts and automatically re-naming files and such. I don't even know if it would work in a virtualized system at all. Likely ditching this idea completely.

**Comment by Darkloke** [comment]
I installed and it looks good in the game + with it u can use all (not selecting the ones u like more) replacement textures from skies 4, alternate skies and new starfields even include optional variants if you wish.

Can write here details about how to install it.

**Comment by yooksi** [comment]
@Darkloke Would you be interested in adding this mod to the guide accompanied with instructions on how to use and install it?

**Comment by Darkloke** [comment]
I will post instructions here, but would be nice if someone else with experience of this mod could review and recheck, since i did it first time, but it seems to work w/i problem.

So...
https://www.nexusmods.com/morrowind/mods/44345?tab=files

1. First of all check all requirements, but if u follow the guide u already have this stuff ready.

- MCP 2-2+
- MWSE v0.9.5-alpha.20151016+
- MGE-XE v0.9.10+
- TES3CMD installed in the Data Files/ folder
- Imagemagick 7.0.1-1+ with checked option (while installing) "Add application directory to your system path"
http://www.imagemagick.org/script/download.php

2. Place all files from mods archive "data files" directory in ur game "data files" directory. U can use wrye mash installer as usual, but note that folder MWCMD wont copied that way.
3. Place this files in ur game root folder:

MWCMD_SkyDiversity_CleanSaveGames.cmd
MWCMD_SkyDiversity_RefreshOriginalTextures.CMD
MWCMD.exe
MWCMD.ini
MWCMD_SkyDiversity_global_overrides.ini

4. Add the MWCMD_SkyDiversity.esm and check that it is near the top of your load order (after Morrowind, Tribunal and Bloodmoon .esms but earlier than any other .esm that may add or modify any Regions

5. Add the rainbow_skd shader to the MGE-XE shader chain - open MGEXEgui.exe, click on  "Shader setup..." then "Modding >>>" then double click on "rainbow_skd" in the  "Available Shaders" confirming that it is added to the "Active Shader" list.

6. Start MWCMD.exe instead of Morrowind.exe or for Steam version, start Morrowind normally, alt-tab back to start MWCMD.exe after reaching the main menu.

Here you will see a warning message that mod backed-up original textures and you need to install a replacer for them - Skies .IV for example.

7. Get Skies .IV. But now you have an ability to add all texture replacements and not limit urself with favorites only. Open ur game data files\textures folder. There now u have also this folders:

SkyDiversity_Orig_Moon_and_Stars
SkyDiversity_Orig_Particles
SkyDiversity_Orig_Skies

This folders contain original textures which u can now expand. To de facto expand you need to make some renames while installing weather section mods.

Grab from Skies .IV this parts:

Moons
Particles
Skies - .IV

This will be now ur "base" textures having the same names as original ones. Now lets say u also wish to install optional components from Skies .IV.

Grab "Skies - AoF Skies" and unpack it to some temp folder. Rename this files with this mask for example
"originalfilename_skies4_aof", so u will have something like Tx_Sky_Blight_skies4_aof.dds. Copy this textures to other ones. 

Using above logic u can install now all optional components from Skies .IV and future mods like Alternate Skies and New Starfields - they all will be seen ingame - you can still select the ones you prefer more/best just to hold equal quality and not creating a mess.

8. Recommended but not required to 'Proceed' when prompted on very first new game load SkyDiversity Texture Initialization Script to Generate a Fresh Starting Set of Sky/Moon/Aurora Textures. This process can take some time depending on your CPU.

Well, somehow like this i suppose.

**Comment by yooksi** [comment]
@Darkloke Thank you for writing this but as I've stated in our Discord conversation, if you would like to see this mod included in the guide the best course of action would be to fork the repository, make the changes to the markdown file yourself and do a pull request. It would help us a lot if more people became engaged in directly contributing via pull requests.

And since you've already written these instructions here yourself, it shouldn't be too big of a task to include them in the file itself and make a pull request. Give me a shout on Discord if you need help with going about doing this, I have time more time these days to help you out.
