### ISSUE TITLE
Morrowind visual pack download link

### ISSUE THREAD

**Issue by spiderman19989** [Tyler799/Morrowind-2019#88]
"Morrowind Visual Pack - This is our base mod. It replaces a lot of stuff that still isn't touched by modern mods, mostly because they're not really used often enough to think about replacing. Most of the textures will be overwritten." 

This directs to this link which is not one specific mod. It refreshes with different mods. What am I supposed to do from here?

http://mw.modhistory.com/download-56-6990

**Comment by prengle** [comment]
Great House Fliggerty and Morrowind Modding History are both hosted by the same dude, Fliggerty, and they've both been in various states of disrepair for months now. I'm pretty sure the guide mentions the former being broken but not the latter. You can use the [Wayback Machine](https://web.archive.org/web/20161103125905/http://mw.modhistory.com/download-56-6990) to grab some mods from Morrowind Modding History (some of them are archived, some of them aren't) or you can just grab the Visual Pack from the [Nexus](https://www.nexusmods.com/morrowind/mods/44311/) since someone actually bothered to upload it there ¯\\\_(ツ)_/¯
