### ISSUE TITLE
Add Easy MCM

### ISSUE THREAD

**Issue by Tyler799** [Tyler799/Morrowind-2019#89]
Useful for swapping to GH - MWSE Edition

https://www.nexusmods.com/morrowind/mods/46427?tab=files

**Comment by Darkloke** [comment]
BTW - What about "Herbalism for Purists" mod? It does the same thing - allows to gather plants. but doesnt require to use any graphical patches for plant meshes. Here is an original readme:

Herbalism for Purists makes Morrowind more immersive by allowing
you to 'pick' plants instead of 'opening' them like containers. 
When you pick a plant, you will automatically gather (or fail to
gather) ingredients from it. Also, plants will disappear now once  
they have been harvested so you will no longer have to check every
plant to see if it has respawned. Plants will also regenerate after
a set time (30 days by default) so that you can continue harvesting
them.

What makes this mod different from other Herbalism mods? First and
foremost, it does not change the way Bethesda intended you to play
the game and thus keeping the game balanced. Unlike other mods,
your chances at gathering ingredients from a plant is the same with
this mod activated. Secondly, this mod has been written from scratch
to make sure it runs as fast as possible. In other words, you will
not experience any loss in performance using this mod.

Last of all, this mod incorporates 'Flora Glow' by Nigedo & 
Max_aka_NOBODY and 'Bloated Morrowind' by MagicNakor. Flora Glow 
makes Morrowind visually appealing by illuminating some plants that
should normally glow like Luminus Russula. And Bloated Morrowind
corrects a mistake Bethesda made in forgetting to include Bloat
Spores in the game (They were included but never implemented).

NOTE: If you are already using an Herbalism mod, don't worry!
Herbalism for Purists will detect this and fix your plants so they
won't disappear forever. Just see the note under the Installation
section below.

**Comment by Tyler799** [comment]
I think I visually prefer having the plants be "picked" as opposed to disappear completely. GH-MWSE is quite efficient and much faster than the old GH was. I don't see any reason to at the moment. I could put it in as an alternate though. Also, for things like this, please make a new issue.
